ensure_path('TEXINPUTS', '.:../../tools/tex_template/');
ensure_path('TTFONTS', '.:../../tools/tex_template/');
ensure_path('OPENTYPEFONTS', '.:../../tools/tex_template/');

$pdf_mode=5;
$dvi_mode = 0;
$postscript_mode = 0;
$out_dir = 'build/';
@default_files = ('alt_character-gen.tex');
