ensure_path('TEXINPUTS', '.:../../template/');
ensure_path('TTFONTS', '.:../../template/');
ensure_path('OPENTYPEFONTS', '.:../../template/');

$pdf_mode=5;
$dvi_mode = 0;
$postscript_mode = 0;
$out_dir = 'build/';
@default_files = ('spell_card.tex');
