name: OSE CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_mdbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.32"
      - run: sh tools/ci/build-mdbook.sh 
      - name: Upload mdbook
        uses: actions/upload-artifact@v4
        with:
          name: OSE-fr
          path: |
            book/
            README.md
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile Spell Cards
        uses: xu-cheng/latex-action@v3
        with:
          args: -file-line-error -halt-on-error -interaction=nonstopmode
          root_file: spell_card.tex
          working_directory: Aides/cartes-sorts/
          work_in_root_file_dir: true
      - run: |
          mkdir -p book
          cp Aides/cartes-sorts/build/spell_card.pdf book
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: OSE-pdf
          path: |
            book/
            README.md
  make_page_artifact:
    needs: [build_mdbook, build_latex]
    runs-on: ubuntu-latest
    steps:
    - name: Download mdbook
      uses: actions/download-artifact@v4
      with:
          name: OSE-fr
    - name: Download pdf
      uses: actions/download-artifact@v4
      with:
          name: OSE-pdf
    - name: Upload a Build Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: book
  deploy:
    # Add a dependency to the build job
    needs: make_page_artifact
    if: github.ref == 'refs/heads/master'
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
