name: OSE CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_mdbook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"
      - run: mdbook build
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile Monster Manual
        uses: xu-cheng/latex-action@v2
        with:
          root_file: monster_manual.tex
          working_directory: manuel_monstres-latex/
      - name: Compile Monster Cards
        uses: xu-cheng/latex-action@v2
        with:
          root_file: monster_cards.tex
          working_directory: manuel_monstres-latex/
      - name: Compile Spell Cards
        uses: xu-cheng/latex-action@v2
        with:
          root_file: spell_card.tex
          working_directory: spell_latex/
      - run: |
          mkdir -p book
          cp manuel_monstres-latex/monster_manual.pdf book
          cp manuel_monstres-latex/monster_cards.pdf book
          cp spell_latex/spell_card.pdf book
  make_artifacts:
    needs: [build_mdbook, build_latex]
    runs-on: ubuntu-latest
    steps:
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: github-pages # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: book


