name: OSE CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_tex:
    runs-on: ubuntu-latest
    container: ghcr.io/xu-cheng/texlive-full:latest
    steps:      
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX documents
        run: bash tools/ci/build-tex.sh
      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: OSE-pdf
          path: |
            book/
            README.md
  build_mdbook:
      runs-on: ubuntu-latest
      needs: [build_tex]
      steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Download pdf
        uses: actions/download-artifact@v4
        with:
          name: OSE-pdf
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.32"
      - name: Build mdBook
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          bash tools/ci/gen-mdbook-input.sh
          bash tools/ci/build-mdbook.sh
      - name: Upload mdbook
        uses: actions/upload-artifact@v4
        with:
          name: OSE-fr
          path: |
            book/
            README.md
  make_page_artifact:
    needs: [build_mdbook]
    runs-on: ubuntu-latest
    steps:
    - name: Download mdbook
      uses: actions/download-artifact@v4
      with:
          name: OSE-fr
    - name: Upload a Build Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: book
  deploy:
    # Add a dependency to the build job
    needs: make_page_artifact
    if: github.ref == 'refs/heads/main'
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
